import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {renderResearch,researchFigure,researchManuscript,validateResearch,RESEARCH_PATH,RESEARCH_TITLE} from '../scripts/research-page.mjs';
import {injectAnalytics,stripAnalytics} from '../scripts/analytics.mjs';
const d=JSON.parse(readFileSync('content/research/var-simulation-results.json'));
const html=readFileSync('public'+RESEARCH_PATH+'index.html','utf8');
test('frozen study has exact finite grain, arithmetic and independently reproduced evidence',()=>{
 validateResearch(d);assert.equal(d.simulation_sets,96000);assert.equal(d.generated_observations,264576000);
 const evidence=JSON.parse(readFileSync('docs/research/var-validation.json'));
 assert.equal(createHash('sha256').update(readFileSync('content/research/var-simulation-results.json')).digest('hex'),evidence.aggregate_json_sha256);
 assert.equal(evidence.exact_frozen_results_reproduced,true);assert.equal(evidence.checkpoints.at(-1).pass,true);
 for(const patch of [{rows:d.rows.slice(1)},{rows:[d.rows[0],...d.rows.slice(0,-1)]},{convergence_pass:false}])assert.throws(()=>validateResearch({...d,...patch}));
 assert.throws(()=>validateResearch({...d,rows:d.rows.map((r,i)=>i?r:{...r,breach_mean_pct:NaN})}));
 assert.equal(readFileSync('content/articles/when-var-methods-disagree.md','utf8'),researchManuscript(d));
});
test('all displayed result rows bind to frozen precision and all diagnostic conditions exist',()=>{
 assert.equal((html.match(/data-result=/g)||[]).length,84); // 72 full + 12 main comparison.
 for(const r of d.rows){const key=[r.scenario,r.train,r.confidence,r.method].join('|');const rows=[...html.matchAll(/<tr data-result="([^"]+)">([\s\S]*?)<\/tr>/g)].filter(m=>m[1]===key);assert.ok(rows.length);
  for(const row of rows){const values=[...row[2].matchAll(/<td>([^<]*)<\/td>/g)].map(m=>m[1]);assert.equal(values[3],r.var_median_pct.toFixed(3));assert.equal(values[4],r.var_p25_pct.toFixed(3)+'–'+r.var_p75_pct.toFixed(3));assert.equal(values[5],r.breach_mean_pct.toFixed(3));assert.equal(values[7],r.breach_error_pp.toFixed(3));assert.equal(values[9],r.kupiec_rejection_pct.toFixed(2));}
 }
 assert.match(html,/id="diagnostics"/);assert.equal((html.match(/<caption>/g)||[]).length,6);
});
test('research is one indexable canonical Article with truthful identity and matching dates',()=>{
 const url='https://marketdeck.in'+RESEARCH_PATH;
 assert.equal((html.match(/rel="canonical"/g)||[]).length,1);assert.ok(html.includes(`href="${url}"`));assert.equal((html.match(/<h1\b/g)||[]).length,1);
 const graph=JSON.parse(html.match(/application\/ld\+json">([\s\S]*?)<\/script>/)[1])['@graph'];assert.deepEqual(graph.map(n=>n['@type']),['WebPage','Article','BreadcrumbList']);const a=graph[1];assert.equal(a.headline,RESEARCH_TITLE);assert.deepEqual(a.author,{'@id':'https://marketdeck.in/#organization'});assert.equal(a.datePublished,'2026-10-04');assert.equal(a.dateModified,a.datePublished);assert.equal(a.version,'INT-VAR-SIM-1.0');assert.equal((html.match(/datetime="2026-10-04"/g)||[]).length,3);
 assert.doesNotMatch(html,/<meta name="robots"[^>]*noindex|FAQPage|Dataset|aggregateRating|priceTarget/);
 assert.equal((readFileSync('public/sitemap.xml','utf8').match(new RegExp(url,'g'))||[]).length,1);
});
test('GA4 stays once and canonical-only; review representation stays noindex/uninstrumented',()=>{
 assert.equal((html.match(/gtag\('config'/g)||[]).length,1);assert.ok(html.includes(`page_location: "https://marketdeck.in${RESEARCH_PATH}"`));assert.equal(injectAnalytics(html),html);
 const review=renderResearch(d,{review:true}).html;assert.match(review,/noindex, nofollow/);assert.doesNotMatch(review,/rel="canonical"/);assert.equal(injectAnalytics(review),review);assert.doesNotMatch(stripAnalytics(html),/gtag\(/);
});
test('research figures exactly match generated bytes, units, captions and selected data',()=>{
 for(const [file,kind,mobile] of [['var-thresholds.svg','threshold',false],['var-breaches.svg','breach',false],['var-thresholds-mobile.svg','threshold',true],['var-breaches-mobile.svg','breach',true]]){
  const svg=readFileSync('public/assets/research/'+file,'utf8');assert.equal(svg,researchFigure(d,kind,{mobile}));assert.match(svg,/<title id="title">/);assert.match(svg,/<desc id="desc">/);assert.doesNotMatch(svg,/<script|https?:\/\/[^\"]+\.js/);
  for(const r of d.rows.filter(r=>r.train===1260&&r.confidence===.99))assert.ok(svg.includes((kind==='breach'?r.breach_mean_pct:r.var_median_pct).toFixed(3)));
 }
 assert.equal((html.match(/<figcaption>/g)||[]).length,2);assert.match(html,/loss threshold in percent per synthetic observation/);
});
test('rights, product distinction, limitations and reproducibility are explicit, with safe links',()=>{
 for(const text of ['No NSE/BSE','in-sample','out-of-sample simulation','not a persistent volatility regime','no universal winner','No material corrections','role 0 estimates','264,576,000'])assert.ok(html.includes(text),text);
 const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.equal(new Set(ids).size,ids.length);
 for(const m of html.matchAll(/href="#([^"]+)"/g))assert.ok(ids.includes(m[1]));
 assert.doesNotMatch(html,/href="[^\"]*(?:account|upload|\/portfolio\/|token=)/i);
 const source=readFileSync('scripts/research/var_simulation.py','utf8');assert.doesNotMatch(source,/requests|urllib|psycopg|django|https?:\/\//);
});
test('discovery labels research honestly without changing four cornerstone guides',()=>{
 for(const path of ['public/index.html','public/intelligence/index.html','public/intelligence/library/index.html']){const page=readFileSync(path,'utf8');assert.ok(page.includes(`href="${RESEARCH_PATH}"`));assert.match(page,/Original research|ORIGINAL RESEARCH/);}
 const hub=readFileSync('public/intelligence/portfolio-analysis/index.html','utf8');assert.equal((hub.match(/class="pa-intel-guide"/g)||[]).length,4);
});
test('research handoff measurement is public-only and contains no private payload',()=>{
 const js=readFileSync('public/research-note.js','utf8');assert.match(js,/research_product_handoff/);assert.match(js,/portfolio_analysis_overview/);assert.doesNotMatch(js,/localStorage|sessionStorage|document\.cookie|location\.search|fetch\(|setInterval/);
 assert.ok(html.includes('<script src="/research-note.js" defer></script>'));
});
