import { readFileSync, writeFileSync } from 'node:fs';

export const escapeHtml = (value) => String(value).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
export const safeUrl = (value) => {
  if (value == null) return null;
  if (typeof value !== 'string' || /[\s<>"'\\]/.test(value)) throw new Error(`Invalid destination: ${value}`);
  if (/^\/(?!\/)/.test(value) || /^https:\/\/[^/]+/.test(value) || /^mailto:[^@]+@[^@]+\.[^@]+/.test(value)) return escapeHtml(value);
  throw new Error(`Unsupported destination: ${value}`);
};
const data = JSON.parse(readFileSync(new URL('../src/site-data.json', import.meta.url)));
const icon = (name, cls = '') => `<svg class="icon ${cls}" aria-hidden="true"><use href="/assets/icons.svg#${escapeHtml(name)}"></use></svg>`;
const arrow = icon('arrow');
const external = url => url.startsWith('https:') ? ' target="_blank" rel="noopener noreferrer"' : '';
const destination = (url, label, cls = 'text-link', pending = 'Link coming soon') => url
  ? `<a class="${cls}" href="${safeUrl(url)}"${external(url)}>${escapeHtml(label)}${arrow}</a>`
  : `<span class="pending">${icon('clock')} ${pending}</span>`;

const productNav = data.products.map(p => `<a class="product-rail-item ${p.color}" href="#product-${p.id}">${icon(p.icon)}<span>${escapeHtml(p.name)}<small>${escapeHtml(p.category)}</small></span>${icon('arrow-up')}</a>`).join('');
const productTabs = data.products.map((p, i) => `<a href="#product-${p.id}" class="product-tab ${p.color}${i === 0 ? ' is-active' : ''}" id="tab-${p.id}" data-product="${p.id}">${icon(p.icon)}<span>${escapeHtml(p.name)}</span></a>`).join('');

const illustrations = {
  stockproof: `<div class="research-ui"><div class="mock-topline"><span>${icon('fundamentals')} STOCKPROOF / RESEARCH WORKSPACE</span><span class="visual-label">WORKFLOW PREVIEW</span></div><div class="research-heading"><span class="company-mark">${icon('building')}</span><div><strong>The business behind the stock</strong><span>Fundamentals. Context. Source material.</span></div>${icon('bookmark')}</div><div class="research-tabs"><span class="selected">Overview</span><span>Financials</span><span>Compare</span><span>Source trace</span></div><div class="research-flow"><div class="document-lines"><span class="mini-label">FINANCIAL FILINGS</span><i></i><i></i><i></i><i></i><span class="source-badge">${icon('document')} Source material</span></div><div class="flow-connection">${icon('arrow')}</div><div class="evidence-list"><div>${icon('check')}<span>Understand the business</span></div><div>${icon('check')}<span>Compare the fundamentals</span></div><div>${icon('check')}<span>Return to the evidence</span></div></div></div><div class="mock-footer">${icon('shield')} A research process you can follow.</div></div>`,
  charting: `<div class="research-ui"><div class="mock-topline"><span>${icon('chart')} CHARTING / MARKET WORKSPACE</span><span class="visual-label">ILLUSTRATIVE</span></div><div class="research-heading"><div><strong>Price tells part of the story.</strong><span>Bring trend and context into the same view.</span></div></div><div class="research-tabs"><span class="selected">Price history</span><span>Indicators</span><span>Market context</span></div><svg class="chart-illustration" viewBox="0 0 600 180" role="img" aria-label="Illustrative price trend, not market data"><path class="gridline" d="M0 30H600M0 75H600M0 120H600M0 165H600M60 0V180M180 0V180M300 0V180M420 0V180M540 0V180"/><path class="chart-secondary" d="M0 145C60 140 90 160 130 135S210 100 260 110S310 125 360 90S420 85 470 65S540 85 600 35"/><path class="chart-primary" d="M0 135L20 139L40 118L60 128L80 100L100 115L120 107L140 121L160 87L180 98L200 80L220 105L240 70L260 80L280 63L300 95L320 88L340 111L360 66L380 75L400 48L420 65L440 40L460 53L480 33L500 52L520 36L540 48L560 22L580 36L600 12"/></svg><div class="mock-footer">${icon('chart')} A clearer picture. A more informed question.</div></div>`,
  fno: `<div class="research-ui"><div class="mock-topline"><span>${icon('layers')} F&O / STRATEGY WORKSPACE</span><span class="visual-label">ILLUSTRATIVE</span></div><div class="research-heading"><div><strong>Explore the shape of a strategy.</strong><span>Consider risk alongside potential outcomes.</span></div></div><div class="research-tabs"><span class="selected">Payoff view</span><span>Option chain</span><span>Strategy analysis</span></div><svg class="chart-illustration payoff" viewBox="0 0 600 180" role="img" aria-label="Illustrative options payoff shape, not a trade recommendation"><path class="gridline" d="M0 30H600M0 75H600M0 120H600M0 165H600M60 0V180M180 0V180M300 0V180M420 0V180M540 0V180"/><path class="chart-secondary" d="M0 95H600"/><path class="chart-primary" d="M20 140H210L390 40H580"/><circle cx="300" cy="90" r="6" fill="currentColor"/></svg><div class="mock-footer">${icon('shield')} Explore scenarios before forming a view.</div></div>`,
  commentary: `<div class="research-ui"><div class="mock-topline"><span>${icon('message')} COMMENTARY / RESEARCH CONTEXT</span><span class="visual-label">WORKFLOW PREVIEW</span></div><div class="research-heading"><div><strong>Ideas deserve their full context.</strong><span>Follow a theme back to the conversation.</span></div></div><div class="topic-tags"><span>Company outlook</span><span>Capital expenditure</span><span>Demand</span><span>Industry trends</span></div><div class="narrative"><span class="quote-symbol">“</span><p>The question is only the beginning.<br>Explore the perspectives behind it.</p></div><div class="mock-footer">${icon('document')} Find the source. Read the context. Form your view.</div></div>`,
  crypto: `<div class="research-ui"><div class="mock-topline"><span>${icon('hexagon')} CRYPTO WORLD / RESEARCH LENS</span><span class="visual-label">WORKFLOW PREVIEW</span></div><div class="research-heading"><div><strong>Look beyond a single asset.</strong><span>Explore how the digital asset ecosystem connects.</span></div></div><div class="crypto-lenses"><div>${icon('globe')}<span>Global markets</span></div><div>${icon('hexagon')}<span>Digital assets</span></div><div>${icon('document')}<span>Indian context</span></div></div><div class="mock-footer">${icon('book')} Build understanding before forming conviction.</div></div>`
};
const productPanels = data.products.map((p, i) => `<article class="product-panel ${p.color}" id="product-${p.id}" data-panel="${p.id}"><div class="product-copy"><span class="eyebrow">0${i + 1} / ${escapeHtml(p.category)}</span><h3>${escapeHtml(p.headline)}</h3><p>${escapeHtml(p.description)}</p><ul class="feature-list">${p.features.map(f => `<li>${icon('check')}${escapeHtml(f)}</li>`).join('')}</ul>${destination(p.url, p.action, 'button button-primary', 'Product link coming soon')}</div><div class="product-visual">${illustrations[p.id]}</div></article>`).join('');
const communityTabs = data.community.map((g, i) => `<a href="#community-${g.id}" id="community-tab-${g.id}" class="community-tab${i === 0 ? ' is-active' : ''}" data-community="${g.id}">${icon(g.icon)}<span>${escapeHtml(g.name)}</span>${arrow}</a>`).join('');
const communityPanels = data.community.map(g => `<div class="community-panel" id="community-${g.id}" data-community-panel="${g.id}"><span class="eyebrow">${escapeHtml(g.name)}</span><h3>${escapeHtml(g.label)}</h3><p>${escapeHtml(g.description)}</p><ul class="platform-list">${g.platforms.map(p => `<li>${p.url ? `<a href="${safeUrl(p.url)}"${external(p.url)}>${escapeHtml(p.name)}${icon('arrow-up')}</a>` : `<span class="platform-unavailable">${escapeHtml(p.name)}<span class="sr-only"> — official link coming soon</span><span class="platform-dot" aria-hidden="true"></span></span>`}</li>`).join('')}</ul><p class="availability-note">${icon(g.platforms.every(p => p.url) ? 'check' : 'clock')} ${g.platforms.every(p => !p.url) ? 'Official channel links are coming soon.' : g.platforms.some(p => !p.url) ? 'More official channel links are coming soon.' : 'Explore our official channels.'}</p></div>`).join('');
const contacts = data.contact.map(c => `<article class="contact-card">${icon(c.icon)}<h3>${escapeHtml(c.name)}</h3><p>${escapeHtml(c.description)}</p>${destination(c.url, c.name, 'text-link', 'Contact channel coming soon')}</article>`).join('');
const footerProducts = data.products.map(p => `<li>${p.url ? `<a href="${safeUrl(p.url)}">${escapeHtml(p.name)}</a>` : `<span>${escapeHtml(p.name)}<small>Coming soon</small></span>`}</li>`).join('');
const legal = Object.entries(data.legal).map(([key, url]) => url ? `<a href="${safeUrl(url)}">${key === 'privacy' ? 'Privacy' : 'Terms'}</a>` : `<span>${key === 'privacy' ? 'Privacy' : 'Terms'} <small>(soon)</small></span>`).join('');
const newsletter = data.newsletter.url ? `<a class="button button-primary" href="${safeUrl(data.newsletter.url)}"${external(data.newsletter.url)}>Join the MarketDeck Brief${arrow}</a>` : `<span class="coming-soon-pill">${icon('clock')} The Brief is coming soon</span>`;
const newsletterNote = data.newsletter.url ? '<span>Research and learning, delivered thoughtfully.</span>' : '<span>No subscriptions are being collected yet.</span>';
const schema = { '@context': 'https://schema.org', '@type': 'WebSite', 'name': data.brand.name, 'url': data.brand.url, 'description': 'Indian market research, charting, derivatives, commentary, and digital asset research in one connected product suite.', 'inLanguage': 'en-IN' };
let html = readFileSync(new URL('../src/index.template.html', import.meta.url), 'utf8');
for (const [key, value] of Object.entries({ PRODUCT_NAV: productNav, PRODUCT_TABS: productTabs, PRODUCT_PANELS: productPanels, COMMUNITY_TABS: communityTabs, COMMUNITY_PANELS: communityPanels, CONTACTS: contacts, FOOTER_PRODUCTS: footerProducts, LEGAL: legal, NEWSLETTER: newsletter, NEWSLETTER_NOTE: newsletterNote, SCHEMA: JSON.stringify(schema).replace(/</g, '\\u003c') })) html = html.replaceAll(`{{${key}}}`, value);
if (/\{\{\w+\}\}/.test(html)) throw new Error('Unresolved template token');
writeFileSync(new URL('../public/index.html', import.meta.url), html);
console.log('Built public/index.html from src/site-data.json and src/index.template.html');
