/** Static editorial views. No runtime fetch, third-party code or publication side effects. */
import {readFileSync,existsSync} from 'node:fs';
export const TOPICS = Object.freeze({'ai-quant':'AI & Quant',equities:'Equities',markets:'Markets',fno:'F&O',india:'India',crypto:'Crypto','research-craft':'Research craft'});
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const text=v=>String(v??'').replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim();
export function localPath(value){
  if(typeof value!=='string'||!/^\/(?!\/)[A-Za-z0-9/_@.\-]+$/.test(value)||value.split('/').includes('..'))throw new Error('Invalid editorial path');
  return value;
}
const slug=v=>{if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(v??''))throw new Error('Invalid editorial slug');return v;};
const topics=v=>{const ts=v??['research-craft'];if(!Array.isArray(ts)||ts.length===0||ts.some(t=>!Object.hasOwn(TOPICS,t)))throw new Error('Unknown editorial topic');return [...new Set(ts)];};
export const readingTime=v=>Math.max(1,Math.ceil(text(v).split(/\s+/).filter(Boolean).length/220));
const humanDate=d=>d&&/^\d{4}-\d{2}-\d{2}$/.test(d)?new Intl.DateTimeFormat('en-IN',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'}).format(new Date(d+'T00:00:00Z')):'';
export function catalog(manifest,notes,{read=path=>JSON.parse(readFileSync(path,'utf8')),exists=path=>existsSync('public'+path)}={}){
  const items=[];const seen=new Set();
  for(const i of manifest.issues){
    if(i.publicationStatus!=='published'||!i.approvedAt)continue;
    const id=slug(i.slug),path='/intelligence/issues/'+id+'/';
    const cover=localPath(i.cover),pdf=i.pdfPath?localPath(i.pdfPath):null;
    if(!exists(cover)||(pdf&&!exists(pdf)))throw new Error('Missing published editorial asset: '+id);
    if(pdf&&(!Number.isInteger(i.pageCount)||i.pageCount<1))throw new Error('Invalid page count');
    items.push({id,path,title:text(i.title),summary:text(i.summary),kind:'magazine',edition:text(i.edition),topics:topics(i.topics),cover,pdf,pages:i.pageCount,minutes:readingTime(read(i.source).pages.map(p=>[p.title,p.intro,p.callout,...(p.sections??[]).flatMap(s=>[s.title,s.text,...(s.items??[])])].filter(Boolean).join(' ')).join(' ')),date:i.publishedAt||i.approvedAt,featured:i.featured!==false});
  }
  const metadata=new Map((manifest.notes??[]).map(n=>[n.slug,n]));
  for(const [index,n] of notes.entries()){
    const id=slug(n.slug),m=metadata.get(id)??{};
    const art=m.coverArt?localPath(m.coverArt):'/assets/india-earth-small.webp';
    if(!exists(art))throw new Error('Missing note artwork');
    items.push({id,path:localPath(n.path),title:text(n.title),summary:text(n.summary),kind:'note',edition:'Learning note '+String(index+1).padStart(2,'0'),topics:topics(m.topics),cover:null,art,pdf:null,pages:null,minutes:readingTime(n.body),date:null,featured:m.featured!==false});
  }
  for(const i of items){if(seen.has(i.id)||!i.title)throw new Error('Duplicate or unnamed editorial item');seen.add(i.id);}
  return items.sort((a,b)=>((b.date??'').localeCompare(a.date??'')));
}
function cover(i,mini=false){
  if(i.cover)return `<img src="${esc(i.cover)}" width="420" height="594" loading="lazy" decoding="async" alt="${mini?'':esc('Cover of '+i.title)}">`;
  return `<span class="intel-note-cover" aria-hidden="true"><span class="intel-book-brand">MarketDeck<span>.</span></span><span class="intel-book-edition">${esc(i.edition)}</span><strong>${esc(i.title)}</strong><img src="${esc(i.art)}" width="700" height="400" alt="" loading="lazy" decoding="async"><span class="intel-book-bottom">PERSPECTIVE / RESEARCH / IDEAS</span></span>`;
}
function meta(i){return `${i.kind==='magazine'?'Magazine':'Learning note'}${i.pages?` · ${i.pages} pages`:''} · ${i.minutes} min read${i.date?` · ${esc(humanDate(i.date))}`:''}`;}
function actions(i){return `<div class="intel-actions"><a class="intel-read" href="${esc(i.path)}">Read online <span aria-hidden="true">↗</span></a>${i.pdf?`<a class="intel-pdf" href="${esc(i.pdf)}" type="application/pdf" download aria-label="Download PDF: ${esc(i.title)}">Download PDF <span aria-hidden="true">↓</span><small>${i.pages} pages</small></a>`:'<span class="intel-format">Online edition</span>'}</div>`;}
const availableTopics=items=>Object.entries(TOPICS).filter(([id])=>items.some(i=>i.topics.includes(id)));
function filters(items,id){return `<div class="intel-topics" role="group" aria-label="Filter by topic" hidden data-intel-filters><button type="button" data-intel-topic="all" aria-pressed="true" aria-controls="${id}">All perspectives</button>${availableTopics(items).map(([t,label])=>`<button type="button" data-intel-topic="${t}" aria-pressed="false" aria-controls="${id}">${esc(label)}</button>`).join('')}</div>`;}
export function shelf(items,{id='intelligence-shelf',heading='Ideas worth a closer look.',limit=8}={}){
  items=items.filter(i=>i.featured).slice(0,limit);
  if(!items.length)return `<section class="intel-shelf" id="${id}"><p class="intel-kicker">MARKETDECK INTELLIGENCE</p><h2>${esc(heading)}</h2><p>Our editorial shelf is taking shape.</p><a href="/intelligence/">Explore Intelligence →</a></section>`;
  return `<section class="intel-shelf" id="${id}" data-intel-shelf aria-labelledby="${id}-title"><header class="intel-shelf-heading"><div><p class="intel-kicker">THE MARKETDECK READING ROOM</p><h2 id="${id}-title">${esc(heading)}</h2></div><a class="intel-all" href="/intelligence/">Explore Intelligence <span aria-hidden="true">↗</span></a></header><div class="intel-toolbar">${filters(items,id+'-slides')}<div class="intel-navigation" hidden data-intel-navigation><span data-intel-count aria-hidden="true">01 / ${String(items.length).padStart(2,'0')}</span><button type="button" data-intel-prev aria-label="Previous editorial item" aria-controls="${id}-slides">←</button><button type="button" data-intel-next aria-label="Next editorial item" aria-controls="${id}-slides">→</button></div></div><div class="intel-slides" id="${id}-slides">${items.map((i,n)=>`<article class="intel-feature" id="${id}-slide-${n}" data-intel-slide data-topic="${i.topics.join(' ')}" data-title="${esc(i.title)}" aria-labelledby="${id}-item-${n}"><div class="intel-cover-stage"><span class="intel-cover-rule" aria-hidden="true"></span><a class="intel-cover" href="${esc(i.path)}" tabindex="-1" aria-hidden="true">${cover(i)}</a><span class="intel-edition-mark">${esc(i.kind==='magazine'?'THE MARKETDECK BRIEF':i.edition)}</span></div><div class="intel-feature-copy"><p class="intel-kicker">${esc(i.topics.map(t=>TOPICS[t]).slice(0,2).join(' / '))}</p><h3 id="${id}-item-${n}">${esc(i.title)}</h3><p class="intel-meta">${meta(i)}</p><p class="intel-summary">${esc(i.summary)}</p>${actions(i)}<p class="intel-feature-foot">${i.pdf?'A visual edition to read, save and revisit.':'One useful idea. A more considered research process.'}</p></div></article>`).join('')}</div><p class="intel-empty" data-intel-empty hidden>No published entries in this topic yet.</p><div class="intel-rail-wrap" hidden data-intel-rail-wrap><p class="intel-rail-label">ON THE SHELF <span>Choose a perspective</span></p><div class="intel-rail" role="group" aria-label="Choose an editorial item">${items.map((i,n)=>`<button type="button" class="intel-thumb" data-intel-index="${n}" aria-controls="${id}-slide-${n}" aria-pressed="false"><span class="intel-thumb-cover">${cover(i,true)}</span><span class="intel-thumb-copy"><small>${i.kind==='magazine'?'THE BRIEF':esc(i.edition).toUpperCase()}</small><strong>${esc(i.title)}</strong><span>${i.pdf?'HTML + PDF':'HTML'} <span aria-hidden="true">↗</span></span></span></button>`).join('')}</div></div><div class="intel-shelf-footer"><p>Read. Question. Go deeper.</p><a href="/intelligence/issues/">Browse the magazine archive <span aria-hidden="true">→</span></a></div><p class="sr-only" aria-live="polite" aria-atomic="true" data-intel-status></p></section>`;
}
export function library(items,{id='reading-library',magazinesOnly=false}={}){
  return `<section class="intel-library" data-intel-library id="${id}" aria-labelledby="${id}-title"><div class="intel-library-heading"><div><p class="intel-kicker">${magazinesOnly?'EVERY PUBLISHED EDITION':'FROM THE EDITORIAL DESK'}</p><h2 id="${id}-title">${magazinesOnly?'The complete collection.':'Find your next perspective.'}</h2></div><p data-intel-results>${items.length} ${items.length===1?'entry':'entries'}</p></div><div class="intel-library-tools" hidden data-intel-library-tools><label class="intel-search"><span>Search the ${magazinesOnly?'archive':'library'}</span><input type="search" data-intel-search placeholder="Search a title, topic or idea…" maxlength="160" autocomplete="off" aria-controls="${id}-grid"></label>${magazinesOnly?'':`<label class="intel-select"><span>Format</span><select data-intel-kind aria-controls="${id}-grid"><option value="all">All formats</option><option value="magazine">Magazines</option><option value="note">Learning notes</option></select></label>`}<button type="button" class="intel-reset" data-intel-reset>Reset filters</button></div>${filters(items,id+'-grid')}<div class="intel-library-grid" id="${id}-grid">${items.map(i=>`<article class="intel-library-card" data-intel-entry data-topic="${i.topics.join(' ')}" data-kind="${i.kind}" data-search="${esc([i.title,i.summary,i.edition,...i.topics.map(t=>TOPICS[t])].join(' '))}"><a class="intel-library-art" href="${esc(i.path)}" tabindex="-1" aria-hidden="true"><span>${cover(i)}</span><em>${i.pdf?'HTML + PDF':'LEARNING NOTE'}</em></a><div class="intel-library-copy"><p class="intel-kicker">${esc(TOPICS[i.topics[0]])}</p><h3><a href="${esc(i.path)}">${esc(i.title)}</a></h3><p class="intel-meta">${meta(i)}</p><p>${esc(i.summary)}</p>${actions(i)}</div></article>`).join('')}</div><div class="intel-empty" data-intel-empty ${items.length?'hidden':''}><h3>No matching perspectives.</h3><p>Try another search or reset the filters.</p></div><button type="button" class="intel-load" hidden data-intel-more>Show more perspectives ↓</button><p class="sr-only" aria-live="polite" aria-atomic="true" data-intel-status></p></section>`;
}
export function editorialPage({body,title,description,path,review=false,archive=false,items=[]}){
  const schema={'@context':'https://schema.org','@type':'CollectionPage',name:title,url:'https://marketdeck.in'+path,description,inLanguage:'en-IN',mainEntity:{'@type':'ItemList',itemListElement:items.map((i,n)=>({'@type':'ListItem',position:n+1,url:'https://marketdeck.in'+i.path,name:i.title}))}};
  return `<!doctype html><html lang="en-IN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} | MarketDeck Intelligence</title><meta name="description" content="${esc(description)}"><meta name="theme-color" content="#080c12">${review?'<meta name="robots" content="noindex, nofollow">':`<link rel="canonical" href="https://marketdeck.in${path}">`}<link rel="icon" href="/assets/favicon.svg"><link rel="stylesheet" href="/home.css"><link rel="stylesheet" href="/intelligence-shelf-v1.css"><script src="/intelligence-shelf-v1.js" defer></script><script type="application/ld+json">${JSON.stringify(schema).replace(/</g,'\\u003c')}</script></head><body class="intel-page"><a class="skip-link" href="#reading">Skip to reading</a><header class="intel-page-header"><a class="brand" href="/" aria-label="MarketDeck home"><svg class="brand-icon" aria-hidden="true"><use href="/assets/icons.svg#brand"></use></svg><span>MarketDeck<span class="brand-period">.</span></span></a><nav aria-label="Editorial navigation"><a href="/intelligence/" ${archive?'':'aria-current="page"'}>Intelligence</a><a href="/intelligence/issues/" ${archive?'aria-current="page"':''}>Issue archive</a><a href="/#products">The product suite <span aria-hidden="true">↗</span></a></nav></header><main id="reading" class="intel-page-main">${body}</main><footer class="intel-page-footer"><span>MarketDeck · Research and education. Not investment advice.</span><a href="/">Return to MarketDeck ↗</a></footer></body></html>`;
}
export function hub(items,{review=false}={}){
  const magazines=items.filter(i=>i.kind==='magazine').length,notes=items.length-magazines;
  const body=`<div class="intel-page-intro"><div><p class="intel-kicker">MARKETDECK INTELLIGENCE</p><h1>Stay curious.<br><span>Go deeper.</span></h1></div><div class="intel-page-deck"><p>Research, ideas and perspective.<br>For a more considered view of the markets.</p><div class="intel-statline"><span><strong>${String(magazines).padStart(2,'0')}</strong> ${magazines===1?'magazine':'magazines'}</span><span><strong>${String(notes).padStart(2,'0')}</strong> learning notes</span><span>Read online.<br>Keep the PDF.</span></div></div></div>${shelf(items,{id:'featured-reading',heading:'On the editorial shelf.'})}${library(items)}<aside class="intel-editorial-note"><p class="intel-kicker">THE MARKETDECK APPROACH</p><p>More context. Better questions.<br><em>Not another prediction.</em></p><span>Our publications are research companions, not investment recommendations.</span></aside>`;
  return editorialPage({body,title:'Research, ideas and perspective',description:'Explore the MarketDeck Brief and original learning notes. Read research online, browse by topic and download available magazine editions.',path:'/intelligence/',review,items});
}
export function archivePage(items,{review=false}={}){
  const magazines=items.filter(i=>i.kind==='magazine');
  return editorialPage({body:`<div class="intel-page-intro intel-archive-intro"><div><p class="intel-kicker">THE MARKETDECK BRIEF</p><h1>The issue<br><span>archive.</span></h1></div><div class="intel-page-deck"><p>Ideas with room to breathe.<br>Every published edition, in one place.</p><p class="intel-meta">${magazines.length} published ${magazines.length===1?'issue':'issues'} · Read online / Download PDF</p><a class="intel-all" href="/intelligence/">Explore all learning notes ↗</a></div></div>${library(magazines,{id:'issue-archive',magazinesOnly:true})}`,title:'The MarketDeck Brief archive',description:'Browse every published MarketDeck Brief. Find research by topic and read the HTML edition or download the designed PDF.',path:'/intelligence/issues/',review,archive:true,items:magazines});
}
