/** One Intelligence-owned original-research note, rendered from frozen generated results. */
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {resolve,dirname} from 'node:path';
import {MARKETDECK,canonicalUrl,webPageNode,organizationReference,compactOrganization,websiteReference} from './structured-identity.mjs';
export const RESEARCH_PATH='/intelligence/notes/when-var-methods-disagree/';
export const RESEARCH_TITLE='When Portfolio VaR Methods Disagree: A Reproducible Simulation';
export const RESEARCH_SUMMARY='Historical, Gaussian and Cornish-Fisher VaR under controlled skew and fat tails: 96,000 generated estimation/holdout pairs, with full results and reproducible code.';
const DATE='2026-10-04', VERSION='INT-VAR-SIM-1.0';
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const f=(v,n=3)=>Number(v).toFixed(n);
const methods=['Historical','Gaussian','Cornish-Fisher'];
const sourceBase='https://github.com/sarthakk-1126/marketdeck-web/blob/research-var-sim-1.0/';
export function validateResearch(d){
  if(d.method_version!==VERSION||d.replications_per_condition!==8000||!d.convergence_pass||d.rows.length!==72)throw Error('Unaccepted research run');
  const seen=new Set();
  for(const r of d.rows){
    const key=[r.scenario,r.train,r.confidence,r.method].join('|');
    if(seen.has(key)||!d.scenarios.includes(r.scenario)||!d.train_sizes.includes(r.train)||!d.confidences.includes(r.confidence)||!methods.includes(r.method))throw Error('Invalid result grain');
    seen.add(key);
    for(const [k,v] of Object.entries(r))if(typeof v==='number'&&!Number.isFinite(v))throw Error('Nonfinite result '+k);
    if(!(r.var_p25_pct<=r.var_median_pct&&r.var_median_pct<=r.var_p75_pct)||Math.abs(r.breach_error_pp-(r.breach_mean_pct-100*(1-r.confidence)))>1e-10)throw Error('Result arithmetic mismatch');
    if(r.breach_mean_pct<0||r.breach_mean_pct>100||r.kupiec_rejection_pct<0||r.kupiec_rejection_pct>100)throw Error('Rate outside bounds');
  }
  return d;
}
export function researchFigure(d,kind,{mobile=false}={}){
  const breach=kind==='breach',max=breach?3.5:4.5;
  const title=breach?'Independent holdout breach rates':'Estimated 99% loss thresholds';
  const desc=breach?'Mean breach percentages for each method and generated distribution. Target: 1%.':'Median VaR percentages for each method and generated distribution.';
  const color=['#8fbcff','#67d8c1','#f4bb79'];
  if(mobile){
    const x=v=>30+v/max*420;
    let body=`<rect width="560" height="800" fill="#0d1420"/><g font-family="Arial,sans-serif" fill="#dbe5f2"><text x="22" y="38" font-size="24">${title}</text><text x="22" y="68" font-size="17">n = 1,260 · 8,000 repetitions · 99% confidence</text>`;
    for(let tick=0;tick<=max;tick+=.5)body+=`<path d="M${x(tick)} 108V654" stroke="#293548"/><text x="${x(tick)}" y="681" font-size="17" text-anchor="middle">${f(tick,1)}</text>`;
    if(breach)body+=`<path d="M${x(1)} 106V654" stroke="#fff" stroke-dasharray="6 4"/><text x="${x(1)+8}" y="104" font-size="17">1% target</text>`;
    d.scenarios.forEach((s,i)=>{body+=`<text x="22" y="${126+i*133}" font-size="22">${esc(s)}</text>`;methods.forEach((m,j)=>{const r=d.rows.find(r=>r.scenario===s&&r.train===1260&&r.confidence===.99&&r.method===m);const v=breach?r.breach_mean_pct:r.var_median_pct,y=140+i*133+j*29;body+=`<rect x="30" y="${y}" width="${x(v)-30}" height="20" fill="${color[j]}"/><text x="${x(v)+8}" y="${y+17}" font-size="18">${f(v)}</text>`;});});
    body+=`<text x="22" y="718" font-size="18">${breach?'Mean holdout breach rate (%)':'Median loss per synthetic observation (%)'}</text>`;
    methods.forEach((m,j)=>body+=`<rect x="${22+j*177}" y="751" width="14" height="14" fill="${color[j]}"/><text x="${42+j*177}" y="765" font-size="16">${m}</text>`);
    return `<svg xmlns="http://www.w3.org/2000/svg" width="560" height="800" viewBox="0 0 560 800" role="img" aria-labelledby="title desc"><title id="title">${title}</title><desc id="desc">${desc} Same data as desktop figure and accessible comparison table.</desc>${body}</g></svg>`;
  }
  const x=v=>250+Math.max(0,v)/max*555;
  let content=`<rect width="960" height="560" fill="#0d1420"/><g font-family="Arial,sans-serif" fill="#dbe5f2"><text x="28" y="40" font-size="25">${title}</text><text x="28" y="68" font-size="16">1,260 estimation observations · 8,000 repetitions · 99% confidence</text>`;
  for(let tick=0;tick<=max;tick+=.5)content+=`<path d="M${x(tick)} 102V468" stroke="#293548"/><text x="${x(tick)}" y="490" font-size="14" text-anchor="middle">${f(tick,1)}</text>`;
  if(breach)content+=`<path d="M${x(1)} 94V468" stroke="#fff" stroke-dasharray="6 4"/><text x="${x(1)+8}" y="104" font-size="14">1% target</text>`;
  d.scenarios.forEach((s,i)=>{
    content+=`<text x="24" y="${146+i*87}" font-size="17">${esc(s)}</text>`;
    methods.forEach((m,j)=>{const r=d.rows.find(r=>r.scenario===s&&r.train===1260&&r.confidence===.99&&r.method===m);const v=breach?r.breach_mean_pct:r.var_median_pct;const y=115+i*87+j*22;
      content+=`<rect x="250" y="${y}" width="${x(v)-250}" height="15" fill="${color[j]}"/><text x="${x(v)+8}" y="${y+13}" font-size="14">${f(v)}</text>`;
    });
  });
  content+=`<text x="530" y="518" text-anchor="middle" font-size="16">${breach?'Mean holdout breach rate (%)':'Median estimated loss per synthetic observation (%)'}</text>`;
  methods.forEach((m,j)=>content+=`<rect x="${180+j*235}" y="538" width="12" height="12" fill="${color[j]}"/><text x="${200+j*235}" y="550" font-size="14">${m}</text>`);
  return `<svg xmlns="http://www.w3.org/2000/svg" width="960" height="560" viewBox="0 0 960 560" role="img" aria-labelledby="title desc"><title id="title">${title}</title><desc id="desc">${desc} Values are in the page's accessible comparison table.</desc>${content}</g></svg>`;
}
function table(d,rows,id,caption){
  return `<div class="research-table" tabindex="0" role="region" aria-label="${esc(caption)}"><table id="${id}"><caption>${esc(caption)}</caption><thead><tr>${['Scenario','Train n','Confidence','Method','VaR median %','VaR p25–p75 %','Mean breach %','Median breach %','Error pp','Breach MCSE pp','Kupiec rejection %','Rejection MCSE pp'].map(t=>`<th scope="col">${t}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr data-result="${esc([r.scenario,r.train,r.confidence,r.method].join('|'))}"><th scope="row">${esc(r.scenario)}</th><td>${r.train}</td><td>${f(r.confidence*100,0)}%</td><td>${r.method}</td>${[f(r.var_median_pct),`${f(r.var_p25_pct)}–${f(r.var_p75_pct)}`,f(r.breach_mean_pct),f(r.breach_median_pct),f(r.breach_error_pp),f(r.breach_mean_mcse_pp,4),f(r.kupiec_rejection_pct,2),f(r.kupiec_rejection_mcse_pp,3)].map(v=>`<td>${v}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
}
export function renderResearch(d,{review=false}={}){
  validateResearch(d);
  const canonical=canonicalUrl(RESEARCH_PATH);
  const subset=d.rows.filter(r=>r.train===1260&&r.confidence===.99);
  const get=(s,m,n=1260,c=.99)=>d.rows.find(r=>r.scenario===s&&r.method===m&&r.train===n&&r.confidence===c);
  const v=(s,m)=>f(get(s,m).var_median_pct),b=(s,m)=>f(get(s,m).breach_mean_pct);
  const schema={'@context':'https://schema.org','@graph':[webPageNode(canonical),{'@type':'Article','@id':canonical+'#article',headline:RESEARCH_TITLE,description:RESEARCH_SUMMARY,datePublished:DATE,dateModified:DATE,inLanguage:MARKETDECK.language,author:organizationReference(),publisher:compactOrganization(),isPartOf:websiteReference(),mainEntityOfPage:{'@id':canonical+'#webpage'},image:MARKETDECK.origin+'/assets/research/var-thresholds.svg',articleSection:'Original research',version:VERSION},{'@type':'BreadcrumbList',itemListElement:[['MarketDeck','/'],['Intelligence','/intelligence/'],['Research library','/intelligence/library/'],[RESEARCH_TITLE,RESEARCH_PATH]].map(([name,path],n)=>({'@type':'ListItem',position:n+1,name,item:canonicalUrl(path)}))}]};
  const body=`
  <nav aria-label="Breadcrumb" class="research-breadcrumb"><a href="/">MarketDeck</a> / <a href="/intelligence/">Intelligence</a> / <a href="/intelligence/library/">Research library</a></nav>
  <p class="eyebrow">MARKETDECK INTELLIGENCE / ORIGINAL RESEARCH</p><h1>${RESEARCH_TITLE}</h1>
  <p class="reading-lead">Same theoretical volatility. Different tail shapes. Three estimates that answer the same probability question—but do not always agree.</p>
  <p class="research-dates">Published <time datetime="${DATE}">4 October 2026</time> · Substantively modified <time datetime="${DATE}">4 October 2026</time> · Sources reviewed <time datetime="${DATE}">4 October 2026</time> · <code>${VERSION}</code></p>
  <aside><strong>The direct finding.</strong> In these generated distributions, shape—not just volatility—changes tail thresholds. At 99% confidence with 1,260 estimation observations, median Gaussian VaR stays near 2.32% in all four processes. Historical and Cornish-Fisher move from roughly 2.31–2.32% under normality to 3.90–3.92% in the skew-and-fat-tail mixture. Larger estimates do not guarantee better breach calibration. These are controlled model-behavior results, not forecasts of Indian or other actual market returns.</aside>
  <nav class="research-contents" aria-label="Study contents"><a href="#design">Design</a><a href="#results">Results</a><a href="#scenarios">Interpretation</a><a href="#full-results">All 72 rows</a><a href="#methodology">Methods</a><a href="#reproduce">Reproduce</a><a href="#references">References</a><a href="#version">Version / cite</a></nav>
  <section id="design"><h2>Study design at a glance</h2><dl class="research-facts"><div><dt>Estimation / holdout pairs</dt><dd>96,000</dd></div><div><dt>Repetitions per condition</dt><dd>8,000</dd></div><div><dt>Estimation observations</dt><dd>252 / 756 / 1,260</dd></div><div><dt>Independent holdout</dt><dd>2,000 observations</dd></div><div><dt>Confidence levels</dt><dd>95% / 99%</dd></div><div><dt>Generated observations</dt><dd>264,576,000</dd></div></dl>
  <p>Each process has theoretical mean zero and standard deviation 1% per synthetic observation. We center and scale the generating distribution using its theoretical moments; we do not force every realized estimation sample to have those moments. That leaves estimation noise visible. Each repetition generates one estimation sample and a separately seeded holdout from the same process. All methods and both confidence levels share that pair, so comparisons are paired rather than confounded by different return draws.</p>
  <p>The estimation lengths are familiar as approximately one, three and five trading years, but only as an analogy. No generated observation is an actual trading day. These are scalar synthetic return series, not simulated holdings, a reconstructed investor portfolio or a market-calibrated universe.</p>
  <h3>Four explicit generating processes</h3><ol><li><strong>Normal:</strong> 0.01 × Z, Z ~ N(0,1).</li><li><strong>Negative skew:</strong> skew-normal shape α = −5. Set δ = −5/√26 and X = δ|Z₁| + √(1−δ²)Z₂, with independent standard normals. Return = 0.01 × (X−δ√(2/π))/√(1−2δ²/π).</li><li><strong>Fat tails:</strong> 0.01 × √(6/8) × Student t₈. Population excess kurtosis is 1.5. The fourth moment exists; the eighth does not, making estimated high moments particularly noisy.</li><li><strong>Skew and fat tails:</strong> independently choose X ~ N(0,1) with probability 0.95, or N(−4,2²) with probability 0.05. Return = 0.01 × (X+0.2)/√1.91. This combines a rare negative shock and a larger scale; it is an iid mixture, not a persistent volatility regime.</li></ol>
  <p>No separate regime-switching scenario was added. Temporal persistence, autocorrelation and clustered volatility are outside this experiment; an iid mixture cannot establish results about them.</p></section>
  <section id="results"><h2>Key results: 99% VaR with 1,260 estimation observations</h2><p>VaR is a loss threshold in percent per synthetic observation. The breach target here is 1%. Every rate is aggregated over 8,000 independently generated pairs. p25–p75 describes variation between estimates, not a confidence interval. MCSE is Monte Carlo standard error of the aggregate mean or frequency, not uncertainty about actual markets.</p>
  ${table(d,subset,'comparison-table','Generated simulation results · n = 1,260 · confidence = 99% · holdout = 2,000')}
  <figure id="figure-thresholds"><picture><source media="(max-width:650px)" srcset="/assets/research/var-thresholds-mobile.svg"><img src="/assets/research/var-thresholds.svg" width="960" height="560" alt="Median 99% VaR rises substantially for Historical and Cornish-Fisher under negative skew and the shock mixture; Gaussian remains near 2.32%."></picture><figcaption>Figure 1. Median estimated loss (%) at 99% confidence, n = 1,260. All values are printed in the comparison table. Generated results, not market observations. <a href="#methodology">Methodology</a>.</figcaption></figure>
  <figure id="figure-breaches"><picture><source media="(max-width:650px)" srcset="/assets/research/var-breaches-mobile.svg"><img src="/assets/research/var-breaches.svg" width="960" height="560" loading="lazy" alt="Mean independent holdout breach rates compared with the 1% target: Gaussian reaches 3.110% in the combined mixture; Cornish-Fisher reaches 0.846% under t8 fat tails."></picture><figcaption>Figure 2. Mean holdout breach rate (%) at 99% confidence, n = 1,260. The dashed line is the 1% target, not a recommended risk limit. <a href="#methodology">Methodology</a>.</figcaption></figure></section>
  <section id="scenarios"><h2>Why the methods disagree</h2><h3>Normal returns: similar centers, different estimation dispersion</h3><p>At n = 1,260 and 99%, Historical, Gaussian and Cornish-Fisher median thresholds are ${v('Normal','Historical')}%, ${v('Normal','Gaussian')}% and ${v('Normal','Cornish-Fisher')}%. Their mean breach rates are ${b('Normal','Historical')}%, ${b('Normal','Gaussian')}% and ${b('Normal','Cornish-Fisher')}%. The normal model's mean and standard deviation summarize this generating process well. Historical quantiles instead rely on relatively few tail order statistics; Cornish-Fisher estimates extra moments even when their population values are zero. Similar median estimates therefore need not have the same variability or rejection frequency.</p>
  <h3>Negative skew: the Gaussian shape misses the asymmetric tail</h3><p>Gaussian mean breach frequency rises to ${b('Negative skew','Gaussian')}%, against the 1% target, while Historical reaches ${b('Negative skew','Historical')}% and Cornish-Fisher ${b('Negative skew','Cornish-Fisher')}%. Matching mean and variance does not match a negatively skewed tail. The moment adjustment moves Cornish-Fisher toward the empirical estimate in this particular skew-normal process. That is evidence about this process and truncation—not a universal endorsement of moment correction.</p>
  <h3>Fat tails: larger is not synonymous with correctly calibrated</h3><p>For t₈ at the same n and confidence, Cornish-Fisher's median threshold is ${v('Fat tails','Cornish-Fisher')}%, above Historical's ${v('Fat tails','Historical')}%. Its mean breach rate is ${b('Fat tails','Cornish-Fisher')}%, below the 1% target, while Gaussian is ${b('Fat tails','Gaussian')}%, above it. Under- and over-breaching are both departures from the stated probability claim. A larger threshold may be conservative for coverage, but this test does not assess utility, capital costs or the magnitude of losses beyond the threshold.</p>
  <h3>Combined skew and fat tails: confidence level changes the story</h3><p>At 99%, Historical and Cornish-Fisher median thresholds are ${v('Skew and fat tails','Historical')}% and ${v('Skew and fat tails','Cornish-Fisher')}%, with mean breach rates ${b('Skew and fat tails','Historical')}% and ${b('Skew and fat tails','Cornish-Fisher')}%. Gaussian breaches average ${b('Skew and fat tails','Gaussian')}%. But Cornish-Fisher at 95% averages ${f(get('Skew and fat tails','Cornish-Fisher',1260,.95).breach_mean_pct)}% breaches against a 5% target, and rejects coverage in ${f(get('Skew and fat tails','Cornish-Fisher',1260,.95).kupiec_rejection_pct,2)}% of repetitions. Agreement at one tail probability does not validate the whole distribution.</p>
  <h3>Sample size: fewer observations in the tail</h3><p>A 252-observation estimation sample has only about 2.52 expected observations below a population 1% quantile. At 1,260, that becomes 12.6. These are expectations, not required counts. Interpolation and sampling variation matter at 99%, particularly for Historical VaR. For normal returns, Historical's 99% interquartile width changes from ${f(get('Normal','Historical',252).var_p75_pct-get('Normal','Historical',252).var_p25_pct)} percentage points at n = 252 to ${f(get('Normal','Historical').var_p75_pct-get('Normal','Historical').var_p25_pct)} at n = 1,260. Longer estimation generally reduces dispersion here; it does not eliminate approximation bias or make iid-generated evidence applicable to shifting markets.</p>
  <h3>95% versus 99%: more than a larger multiplier</h3><p>The lower 1% tail has fewer empirical observations and responds differently to kurtosis terms than the lower 5% tail. Do not extrapolate calibration at one confidence level to the other. The full tables expose both levels for every process and sample length. We report no composite score and no universal winner.</p></section>
  <section id="calibration"><h2>Independent holdout calibration and Kupiec</h2><p>For each threshold, a breach is a holdout return strictly less than the negative loss threshold. Its rate has denominator 2,000. The targets are 5% at 95% confidence and 1% at 99%, giving 100 or 20 expected holdout breaches if the threshold equals the true quantile. We apply the deployed Kupiec proportion-of-failures function and reject at p-value &lt; 0.05.</p>
  <p>The test checks unconditional coverage. It does not check breach independence, tail-loss severity, expected shortfall, model stability or investment suitability. Its chi-square reference is asymptotic. Rejection proportions include estimation uncertainty: thresholds are estimated, not known population quantiles. Consequently, even under a normal process the rejection proportion need not equal 5%. Increasing holdout length with estimation length fixed can make small estimation errors easier to detect. A non-rejection is not proof of calibration.</p>
  <p>We flag a material intermethod disagreement when (largest − smallest threshold) / median absolute threshold exceeds 20%, evaluated per repetition. This is a descriptive study convention, not a trading rule. The denominator is the paired repetition count, and identical disagreement rates across methods are deliberate.</p></section>
  <section id="full-results"><h2>Full result tables: all 72 conditions</h2><p>Values are rounded once for display. The linked aggregate JSON retains full precision. Scroll tables horizontally if needed; the page itself remains within the viewport. All rows are present in server-delivered HTML, with no data fetch or account required.</p>
  ${d.scenarios.map((s,i)=>`<h3 id="scenario-${i}">${s}</h3>${table(d,d.rows.filter(r=>r.scenario===s),'results-'+i,`${s} · all estimation lengths and confidence levels · 8,000 repetitions per condition`)}`).join('')}
  <h3>Disagreement and numerical diagnostics</h3><div class="research-table" tabindex="0" role="region" aria-label="Disagreement and numerical diagnostics"><table id="diagnostics"><caption>Rates across 8,000 repetitions · CF flags are process/sample-specific</caption><thead><tr>${['Scenario','Train n','Confidence','Disagree >20% (%)','CF nonmonotone (%)','CF 99% below 95% (%)','Negative VaR: H / G / CF (%)'].map(t=>`<th scope="col">${t}</th>`).join('')}</tr></thead><tbody>${d.rows.filter(r=>r.method==='Historical').map(r=>`<tr><th scope="row">${r.scenario}</th><td>${r.train}</td><td>${f(r.confidence*100,0)}%</td><td>${f(r.disagreement_pct,2)}</td><td>${f(r.cf_nonmonotone_pct,2)}</td><td>${f(r.cf_confidence_crossing_pct,2)}</td><td>${methods.map(m=>f(get(r.scenario,m,r.train,r.confidence).negative_var_pct,2)).join(' / ')}</td></tr>`).join('')}</tbody></table></div>
  <p>No nonfinite estimates, negative thresholds, CF confidence-order crossings or derivative failures were observed in this frozen run. We tested the CF quantile derivative over lower-tail probabilities 0.001–0.1. These diagnostics do not prove the approximation is accurate, valid outside that interval, or stable for another distribution. A finite number is not sufficient validation.</p></section>
  <section id="methodology"><h2>Methodology: known definitions, exact implementation</h2><p>Let c be confidence, q = 1−c, μ the sample mean, s the standard deviation with denominator n−1, and z the standard normal q-quantile. Let mₖ = mean((r−μ)ᵏ), S = m₃/m₂³ᐟ² and K = m₄/m₂²−3. Moment denominators are n, with no sample-bias adjustment. Units below are return fractions; tables multiply by 100.</p>
  <dl><dt>Historical</dt><dd>VaR = −Q(q), empirical quantile with h = (n−1)q and linear interpolation between sorted observations. No nearest-rank substitution.</dd><dt>Gaussian / Parametric</dt><dd>VaR = −(μ + z s).</dd><dt>Cornish-Fisher</dt><dd>zCF = z + (z²−1)S/6 + (z³−3z)K/24 − (2z³−5z)S²/36; VaR = −(μ + zCF s). This specified four-cumulant approximation is not an exact distribution quantile.</dd><dt>Kupiec</dt><dd>p = 1−c, T = 2,000, x = breaches, p̂ = x/T. LR = 2[(T−x) log((1−p̂)/(1−p)) + x log(p̂/p)]. Use 0 log 0 = 0 at boundaries. p-value = erfc(√(LR/2)), equivalent to the upper tail of χ² with one degree of freedom.</dd></dl>
  <p>The frozen pure calculation reference is <a href="https://github.com/sarthakk-1126/StockProof/blob/54da2757850dd520ab9c0734a7689bba2dfce41b/screener/metrics.py">StockProof metrics.py at 54da275</a>. The experiment vectorizes VaR estimation for local compute efficiency and proves agreement with those exact functions at relative tolerance 10⁻¹²; Kupiec calls the reference function directly. No production Portfolio calculation has been changed.</p>
  <p>Invalid sample/confidence/nonfinite input fails validation. Constant samples make moment-based Cornish-Fisher unavailable; they are tested as an edge case and are not among the generated study samples. We do not clip negative thresholds, winsorize observations, rearrange CF quantiles, smooth estimates or silently discard unstable results. Publication fails on a nonfinite output. Missing results are unavailable, not zero.</p>
  <p>Monte Carlo standard error equals the across-repetition sample standard deviation divided by √8,000. For rejection percentages the same rule is applied to the binary rejection indicator and multiplied by 100. These errors describe simulation precision conditional on the design. They do not include uncertainty from choosing the generating processes.</p></section>
  <section id="reproduce"><h2>Reproduce the frozen study</h2><p>Use Python ${d.python} and NumPy ${d.numpy}. No network, credentials, exchange feed or database is needed during calculation. Download/clone the public code and aggregate result file; numerical samples are regenerated rather than distributed as a giant price file.</p><pre><code>python -m pip install numpy==${d.numpy}
python scripts/research/var_simulation.py --replications 8000
python -m unittest discover -s scripts/research -p "test_*.py"
python scripts/research/validate_run.py</code></pre>
  <p>Master seed ${d.seed}. PCG64 receives SeedSequence([${d.seed}, scenario_index, train_length, replication_index, role]). Scenario indices are 0–3 in the design order; replication indices are 0–7,999; role 0 estimates and role 1 holds out. Methods and confidence levels draw no further randomness. Different sample lengths have distinct streams, not nested histories.</p>
  <p>Generated-observation SHA-256, in the script's scenario/sample/repetition order, train then holdout, little-endian float64: <code class="research-hash">${d.generated_returns_sha256}</code>. Floating-point/library changes can alter byte hashes; reproduce with the pinned environment before claiming an exact match.</p>
  <p>A 128-repetition cost pilot took 1.33 seconds locally. The 4,000-repetition run took 43.89 seconds and missed the rejection-frequency split limit (4.30 percentage points versus 4). The 8,000 run took 84.78 seconds and passed all preregistered limits. Maximum equal-half differences were ${f(d.convergence_max_split_difference.median_relative*100,3)}% relative median VaR, ${f(d.convergence_max_split_difference.mean_breach_pp,4)} percentage points mean breaches and ${f(d.convergence_max_split_difference.rejection_pp,3)} percentage points rejection frequency. Checkpoints and exact byte-for-byte rerun evidence are in the validation record. Numerical convergence is not a claim of real-market accuracy.</p>
  <ul><li><a href="${sourceBase}scripts/research/var_simulation.py">Simulation source</a></li><li><a href="${sourceBase}scripts/research/canonical_metrics.py">Frozen calculation reference</a></li><li><a href="${sourceBase}scripts/research/test_var_simulation.py">Formula, equivalence and edge-case tests</a></li><li><a href="${sourceBase}content/research/var-simulation-results.json">All aggregate results, full precision</a></li><li><a href="${sourceBase}docs/research/var-validation.json">Convergence and reproducibility evidence</a></li><li><a href="${sourceBase}docs/research/var-study-contract.md">Study contract and rights register</a></li></ul></section>
  <section id="product"><h2>Relationship to Portfolio Analysis</h2><p>The methods match MarketDeck's conceptual and tested implementation definitions. The current product's Kupiec diagnostic uses the same historical sample used to estimate its threshold: it is <strong>in-sample</strong>. This study estimates on one generated sample and tests on an independently generated holdout: it is <strong>out-of-sample simulation</strong>. Neither is a prospective real-market validation. Product outputs are not silently relabeled as holdout results.</p><p><a href="/intelligence/notes/portfolio-var-historical-parametric-cornish-fisher/">Read the conceptual VaR guide</a>, <a href="/screener/methodology/#portfolio-analysis">verify the product methodology</a>, or <a href="/screener/portfolio-analysis/">explore the public Portfolio Analysis overview</a>. This public study needs no portfolio upload or account.</p></section>
  <section id="limitations"><h2>What this evidence does—and does not—establish</h2><p>The findings isolate distribution shape and estimation-sample effects under fixed iid processes and identical train/holdout laws. Real returns can have changing regimes, dependence, costs, nonlinear holdings, missingness and structural breaks. None is validated here. The fourth scenario changes mixture scale per independent observation but does not model a volatility time series.</p><p>Four deliberately chosen processes are not an exhaustive model comparison. Student t₈ creates noisy higher-moment estimates. Cornish-Fisher truncation can be biased even without a monotonicity flag. Aggregated means can hide rare estimation failures; interquartile ranges omit the most extreme estimates. Kupiec is a limited coverage diagnostic and its rejection fraction is not a probability that a model is “wrong.” We do not assess expected shortfall, forecast profits, recommend a method for every investor, rank portfolios or claim simulated returns represent Indian markets.</p><p>All numerical return inputs, output tables, figures and text are MarketDeck-created. No NSE/BSE observations, third-party price dataset, company financial database or real/private user portfolio data enters this study. Sources below document methods, not borrowed numerical data. Authoring/code assistance does not constitute independent peer review; MarketDeck is the publisher, with no invented researcher credentials or external-review claim.</p></section>
  <section id="references"><h2>Method references and source register</h2><p>Reviewed 4 October 2026. Citation links are methodology references; no source table, empirical dataset, or long excerpt is reproduced.</p><ol><li><a href="https://numpy.org/doc/stable/reference/generated/numpy.quantile.html">NumPy quantile documentation</a> — linear interpolation convention. Execution is pinned to NumPy ${d.numpy}, not whatever version the live documentation later shows.</li><li><a href="https://numpy.org/doc/stable/reference/random/parallel.html">NumPy parallel random generation documentation</a> — SeedSequence and separated streams.</li><li><a href="https://www.itl.nist.gov/div898/handbook/eda/section3/eda35b.htm">NIST: measures of skewness and kurtosis</a> — moment-ratio definitions and excess-kurtosis convention.</li><li><a href="https://www.value-at-risk.net/the-cornish-fisher-expansion/">Glyn Holton: the Cornish-Fisher expansion</a> — cumulant-based quantile approximation and its scope. Our exact specified truncation is printed above; adding moments is not assumed to guarantee improvement.</li><li><a href="https://fedinprint.org/item/fedgfe/34596/original">Paul H. Kupiec (1995), Techniques for verifying the accuracy of risk measurement models</a> — original Federal Reserve working-paper bibliographic record and full-text destination; no claim that the blocked SSRN copy was reviewed.</li><li><a href="https://www.newyorkfed.org/medialibrary/media/research/staff_reports/research_papers/9710.pdf">Jose A. Lopez (1997), Regulatory evaluation of value-at-risk models</a> — primary methodological discussion of coverage-based evaluation.</li><li><a href="/screener/methodology/#portfolio-analysis">MarketDeck product methodology</a> and the pinned code reference — implementation conventions, not independent authority.</li></ol></section>
  <section id="version"><h2>Version, corrections and citation</h2><p><strong>${VERSION}</strong> · First publication: 4 October 2026. No material corrections at initial publication. Interpretation-sensitive changes to formulas, denominators, scenarios or eligibility require a new method version and dated change entry. Corrections identify affected results and reasons; prior entries remain visible. This URL and table/figure anchors remain stable. Cosmetic builds do not advance research dates.</p><p>Suggested citation: MarketDeck Intelligence (2026), “${RESEARCH_TITLE}”, ${VERSION}, published 4 October 2026, ${canonical}. When citing a number, include scenario, estimation n, confidence, method, metric and units; specify synthetic independent-holdout evidence.</p><p>To report an error, <a href="https://github.com/sarthakk-1126/marketdeck-web/issues">open a public issue</a> with the table row and reproduction details. Do not post credentials or private portfolio information.</p></section>`;
  return {body,html:`<!doctype html><html lang="en-IN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${RESEARCH_TITLE} | MarketDeck Intelligence</title><meta name="description" content="${esc(RESEARCH_SUMMARY)}">${review?'<meta name="robots" content="noindex, nofollow">':`<link rel="canonical" href="${canonical}">`}<meta property="og:type" content="article"><meta property="og:title" content="${esc(RESEARCH_TITLE)}"><meta property="og:url" content="${canonical}"><meta property="og:image" content="${MARKETDECK.origin}/assets/research/var-thresholds.svg"><meta property="article:published_time" content="${DATE}"><meta property="article:modified_time" content="${DATE}"><link rel="icon" href="/favicon.png"><link rel="stylesheet" href="/home.css?v=brand-20260926"><link rel="stylesheet" href="/reading.css"><link rel="stylesheet" href="/research-note.css"><script src="/research-note.js" defer></script><script type="application/ld+json">${JSON.stringify(schema).replace(/</g,'\\u003c')}</script></head><body class="research-note"><a class="skip-link" href="#reading">Skip to research</a><header class="reading-header"><a class="brand" href="/" aria-label="MarketDeck home"><img class="brand-icon" src="/assets/marketdeck-mark.png" width="32" height="32" alt="" aria-hidden="true"><span class="brand-wordmark">Market<span class="brand-deck">Deck</span></span></a><nav aria-label="Research navigation"><a href="/intelligence/">Intelligence</a><a href="/intelligence/library/">Library</a><a href="/screener/portfolio-analysis/">Portfolio Analysis</a></nav></header><main id="reading" class="reading-main"><article class="reading-body">${body}</article></main><footer class="reading-footer">MarketDeck · Original research, not investment advice. <a href="/research-standards/">Research standards</a><a href="/intelligence/editorial-policy/">Editorial policy</a></footer></body></html>`};
}
export function buildResearch({root,review=false}){
  const d=validateResearch(JSON.parse(readFileSync('content/research/var-simulation-results.json','utf8')));
  const rendered=renderResearch(d,{review});
  const write=(path,text)=>{const file=resolve(root,'.'+path);mkdirSync(dirname(file),{recursive:true});writeFileSync(file,text);};
  write(RESEARCH_PATH+'index.html',rendered.html);
  write('/assets/research/var-thresholds.svg',researchFigure(d,'threshold'));
  write('/assets/research/var-breaches.svg',researchFigure(d,'breach'));
  write('/assets/research/var-thresholds-mobile.svg',researchFigure(d,'threshold',{mobile:true}));
  write('/assets/research/var-breaches-mobile.svg',researchFigure(d,'breach',{mobile:true}));
  return {slug:'when-var-methods-disagree',path:RESEARCH_PATH,title:RESEARCH_TITLE,summary:RESEARCH_SUMMARY,body:rendered.body};
}

/** Reviewed frozen manuscript for the existing two-registry inventory contract.
 * Generated from the same authored renderer + frozen results, never separately edited.
 * Full precision and all rows remain in JSON and public HTML, not another public URL.
 */
export function researchManuscript(d){
  return '# '+RESEARCH_TITLE+'\n\n'+renderResearch(d).body
    .replace(/<nav\b[\s\S]*?<\/nav>/g,'')
    .replace(/<div class="research-table"[\s\S]*?<\/div>/g,'\nFull results: see the public HTML tables and frozen aggregate JSON.\n')
    .replace(/<h2[^>]*>([\s\S]*?)<\/h2>/g,'\n\n## $1\n\n')
    .replace(/<h3[^>]*>([\s\S]*?)<\/h3>/g,'\n\n### $1\n\n')
    .replace(/<a[^>]+href="([^"]+)"[^>]*>([\s\S]*?)<\/a>/g,(_,url,label)=>`[${label}](${url.startsWith('#')?RESEARCH_PATH+url:url})`)
    .replace(/<\/(?:p|li|dd|aside|figcaption|pre)>/g,'\n\n')
    .replace(/<[^>]*>/g,'').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&')
    .replace(/[ \t]+/g,' ').replace(/\n[ \t]+/g,'\n').replace(/\n{3,}/g,'\n\n').trim()+'\n';
}
